# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Keda' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Keda
  pod 'Stripe'
  pod 'Braintree'
  pod 'BSImagePicker'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'SDWebImage'
  pod 'FBSDKLoginKit'
  pod 'CryptoSwift'
  pod 'Alamofire'
  pod 'MessageKit'

end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        config.build_settings['DYLIB_COMPATIBILITY_VERSION'] = ''
      end
    end
end
